"""add state to businesses

Revision ID: 0d920c3b6087
Revises: 952714456569
Create Date: 2026-07-09 23:26:36.366547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d920c3b6087'
down_revision: Union[str, Sequence[str], None] = '952714456569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('state', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_businesses_state'), 'businesses', ['state'], unique=False)
    op.alter_column('upload_history', 'duplicate_records',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('upload_history', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'PROCESSING'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_history', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'PROCESSING'::character varying"))
    op.alter_column('upload_history', 'duplicate_records',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_businesses_state'), table_name='businesses')
    op.drop_column('businesses', 'state')
    # ### end Alembic commands ###
