"""add state to businesses

Revision ID: 1796f95c109d
Revises: 395bf9363fb8
Create Date: 2026-07-22 16:02:08.784443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1796f95c109d'
down_revision: Union[str, Sequence[str], None] = '395bf9363fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('businesses', 'google_maps_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('businesses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'NEW'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'NEW'::character varying"))
    op.alter_column('businesses', 'google_maps_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('businesses', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('businesses', 'phone_number',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
