"""add attempt_number

Revision ID: 395bf9363fb8
Revises: dd873196f214
Create Date: 2026-07-21 22:20:40.141570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395bf9363fb8'
down_revision: Union[str, Sequence[str], None] = 'dd873196f214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call_logs",
        sa.Column(
            "attempt_number",
            sa.Integer(),
            nullable=False,
            server_default="1"
        )
    )

    op.alter_column(
        "call_logs",
        "attempt_number",
        server_default=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_logs', 'attempt_number')
    # ### end Alembic commands ###
