"""refactor call_logs

Revision ID: 46c0569134bd
Revises: 8b3e3ec8ec41
Create Date: 2026-07-15 21:25:44.867878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46c0569134bd'
down_revision: Union[str, Sequence[str], None] = '8b3e3ec8ec41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('call_logs', sa.Column('lead_assignment_id', sa.Integer(), nullable=True))
    op.add_column('call_logs', sa.Column('call_outcome', sa.String(length=30), nullable=False))
    op.add_column('call_logs', sa.Column('duration', sa.String(length=20), nullable=True))
    op.drop_constraint(op.f('call_logs_business_id_fkey'), 'call_logs', type_='foreignkey')
    op.create_foreign_key(None, 'call_logs', 'lead_assignments', ['lead_assignment_id'], ['id'])
    op.drop_column('call_logs', 'call_status')
    op.drop_column('call_logs', 'business_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_logs', sa.Column('business_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('call_logs', sa.Column('call_status', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.create_foreign_key(op.f('call_logs_business_id_fkey'), 'call_logs', 'businesses', ['business_id'], ['id'])
    op.drop_column('call_logs', 'duration')
    op.drop_column('call_logs', 'call_outcome')
    op.drop_column('call_logs', 'lead_assignment_id')
    
    # ### end Alembic commands ###
