"""add queue reason to daily queue

Revision ID: 61b16292cd46
Revises: 6c7a2477ce8a
Create Date: 2026-07-20 21:42:36.118959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '61b16292cd46'
down_revision: Union[str, Sequence[str], None] = '6c7a2477ce8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_call_queue', sa.Column('queue_reason', sa.String(length=50), nullable=False))
    op.drop_column('daily_call_queue', 'completed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_call_queue', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('daily_call_queue', 'queue_reason')
    # ### end Alembic commands ###
