"""add queue snapshot fields

Revision ID: 6c7a2477ce8a
Revises: 740a861396b5
Create Date: 2026-07-20 20:10:24.695155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7a2477ce8a'
down_revision: Union[str, Sequence[str], None] = '740a861396b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_call_queue', sa.Column('lead_score', sa.Float(), nullable=False))
    op.add_column('daily_call_queue', sa.Column('priority', sa.String(), nullable=False))
    op.add_column('daily_call_queue', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_call_queue', 'completed_at')
    op.drop_column('daily_call_queue', 'priority')
    op.drop_column('daily_call_queue', 'lead_score')
    # ### end Alembic commands ###
