"""add is_deleted to users

Revision ID: 764e8f33f1dd
Revises: 23af7502a0ea
Create Date: 2026-07-19 16:33:48.017531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '764e8f33f1dd'
down_revision: Union[str, Sequence[str], None] = '23af7502a0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('businesses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'NEW'::character varying"))
    op.alter_column('call_logs', 'lead_assignment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.alter_column('call_logs', 'lead_assignment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'status',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'NEW'::character varying"))
    # ### end Alembic commands ###
