"""add call_outcome and updated_at to lead_assignments

Revision ID: 8b3e3ec8ec41
Revises: fa3f1cad41b1
Create Date: 2026-07-15 16:35:37.031370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b3e3ec8ec41'
down_revision: Union[str, Sequence[str], None] = 'fa3f1cad41b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_assignments', sa.Column('call_outcome', sa.String(length=100), nullable=True))
    op.add_column('lead_assignments', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_assignments', 'updated_at')
    op.drop_column('lead_assignments', 'call_outcome')
    # ### end Alembic commands ###
