"""add stored_file_path to upload_history

Revision ID: 952714456569
Revises: ded484e1d968
Create Date: 2026-07-04 01:20:38.756193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '952714456569'
down_revision: Union[str, Sequence[str], None] = 'ded484e1d968'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_history', sa.Column('stored_file_path', sa.String(length=500), nullable=True))
    


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('upload_history', 'stored_file_path')
    
