"""Update business table

Revision ID: af3ada67cacf
Revises: 44826a4503eb
Create Date: 2026-06-30 18:15:10.111822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3ada67cacf'
down_revision: Union[str, Sequence[str], None] = '44826a4503eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('status', sa.String(length=30), server_default="NEW", nullable=False))
    op.add_column('businesses', sa.Column('last_contacted_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('businesses', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('businesses', 'google_maps_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('businesses', 'google_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('businesses', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'businesses', ['google_maps_link'])
    op.create_foreign_key(None, 'businesses', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'businesses', type_='foreignkey')
    op.drop_constraint(None, 'businesses', type_='unique')
    op.alter_column('businesses', 'review_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('businesses', 'google_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('businesses', 'google_maps_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('businesses', 'created_by')
    op.drop_column('businesses', 'last_contacted_at')
    op.drop_column('businesses', 'status')
    op.drop_column('businesses', 'description')
    # ### end Alembic commands ###
