"""business_id unique

Revision ID: f68d6284adc2
Revises: 61b16292cd46
Create Date: 2026-07-20 21:55:38.634269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f68d6284adc2'
down_revision: Union[str, Sequence[str], None] = '61b16292cd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'lead_scores', ['business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lead_scores', type_='unique')
    # ### end Alembic commands ###
